Repository Filiprogrammer/AlphabotSZUCar, pull requests merged in 2021-11, with the labels that each got.

#39 esp32/PrimaryESP32: Make some member functions const
  esp32/PrimaryESP32/alphabot/Compass.cpp
  esp32/PrimaryESP32/alphabot/Compass.h
  esp32/PrimaryESP32/alphabot/DrivingAssistent.cpp
  esp32/PrimaryESP32/alphabot/DrivingAssistent.h
  esp32/PrimaryESP32/alphabot/Navigator.cpp
  esp32/PrimaryESP32/alphabot/Navigator.h
  esp32/PrimaryESP32/alphabot/PositioningSystem.cpp
  esp32/PrimaryESP32/alphabot/PositioningSystem.h
  esp32/PrimaryESP32/alphabot/SaveFile.cpp
  esp32/PrimaryESP32/alphabot/SaveFile.h
  esp32/PrimaryESP32/alphabot/TwoMotorDrive.cpp
  esp32/PrimaryESP32/alphabot/TwoMotorDrive.h
Labels: ESP32, refactoring

#41 esp32/PrimaryESP32: Fix inverted differential
  esp32/PrimaryESP32/alphabot/TwoMotorDrive.cpp
Labels: bug, ESP32

#42 esp32/PrimaryESP32: Refactor BLEHandler & DrivingAssistent
  esp32/PrimaryESP32/alphabot/BLEHandler.cpp
  esp32/PrimaryESP32/alphabot/BLEHandler.h
  esp32/PrimaryESP32/alphabot/DrivingAssistent.cpp
  esp32/PrimaryESP32/alphabot/alphabot.ino
Labels: ESP32, refactoring

#43 docs: Add timestamps to BLE protocol specification
  docs/wifi_ble_communication_protocol.md
Labels: documentation

#45 esp32/PrimaryESP32: Expose BLE service
  esp32/PrimaryESP32/alphabot/BLEHandler.cpp
Labels: enhancement, ESP32

#46 esp32/PrimaryESP32: Fix inverted speed in Navigator
  esp32/PrimaryESP32/alphabot/Navigator.cpp
Labels: bug, ESP32

#35 Implement client library (TCP-Windows)
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/AlphabotClientLibrary.Core.Tcp.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core/AlphabotClientLibrary.Core.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core/Handler/ConnectionHandler.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core/Handler/ObstacleHandler.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core/Handler/ResponseHandler.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/AlphabotClientLibrary.Shared.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/BleUuids.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IConnectionData.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/BleConnectionData.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/BleInformation.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Obstacle.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/WiFiConnectionData.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/RequestInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/AddObstacleRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateSteeringRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/NavigationTargetRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/PingRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveAllObstaclesRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/SpeedSteerRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/TestRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/ResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/CompassResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/DistanceSensorResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ErrorResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MultipleSensorResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/NewObstacleRegisteredResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PathFindingResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PingResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PositioningResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/TestResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.sln
Labels: enhancement

#44 docs: Make TCP & BLE protocol behaviour the same
  docs/wifi_ble_communication_protocol.md
Labels: documentation

#51 docs/protocol: Add timestamp to BLE_CHAR_ANCHOR_LOCATIONS
  docs/wifi_ble_communication_protocol.md
Labels: documentation, enhancement

#48 Adapt client library to new protocol changes
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/BleUuids.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/AddObstacleRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateSteeringRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/NavigationTargetRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveAllObstaclesRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
Labels: enhancement

#52 clientLib: Fix positioning response interpretation
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
Labels: bug

#56 CI: Test the client library with GitHub Actions
  .github/workflows/main.yml
Labels: build system, test

#53 clients: Add TCP unit tests to client library
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/AlphabotClientLibrary.Test.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.sln
Labels: test
