Repository Filiprogrammer/AlphabotSZUCar, pull requests merged in 2021-12, with the labels that each got.

#57 clients: Add response types and small changes
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/WiFiConnectionData.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/SpeedSteerRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/CompassResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/DistanceSensorResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ErrorResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MultipleSensorResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/NewObstacleRegisteredResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PathFindingResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PingResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PositioningResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/TestResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
Labels: enhancement

#59 rpi/sd_image: Free up ttyS1 serial port
  rpi/sd_image/build_in_container.sh
Labels: Raspberry Pi

#54 clients: Add TCP test client and test server
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Client/AlphabotClientLibrary.Test.Tcp.Client.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Client/Program.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/AlphabotClientLibrary.Test.Tcp.Server.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/Program.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.sln
Labels: test

#61 CI: Run client library test workflow on Windows
  .github/workflows/main.yml
Labels: build system, test

#55 clients: Add example WinForms GUI to TCP client
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/AlphabotClientLibrary.Example.WinForms.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/AlphabotClientLibrary.Example.WinForms.csproj.user
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.resx
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/Program.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.sln
Labels: documentation, enhancement

#31 pcb: Add Alphabot ESP32 PCB
  pcb/alphabot_esp32_pcb/AlphabotESP32PCB_BOM_PCBWay.xlsx
  pcb/alphabot_esp32_pcb/AlphabotESP32PCB_Gerber.zip
  pcb/alphabot_esp32_pcb/centroid.csv
Labels: PCB

#62 esp32/PrimaryESP32: Adapt pin assignment to match PCB
  esp32/PrimaryESP32/alphabot/pinconfig.h
Labels: ESP32

#63 docs: Correct length of BLE toggle characteristic
  docs/wifi_ble_communication_protocol.md
Labels: documentation

#68 clients: Fix responses
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/AlphabotClientLibrary.Core.Tcp.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core/AlphabotClientLibrary.Core.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/AlphabotClientLibrary.Shared.csproj
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/ResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PingResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/Program.cs
Labels: bug

#72 docs/protocol: Remove duplicate calibration request
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
  docs/wifi_ble_communication_protocol.md
Labels: documentation
