Repository Filiprogrammer/AlphabotSZUCar, pull requests merged in 2022-01, with the labels that each got.

#71 docs/clients: Add missing sensor responses
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/AccelerometerResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/AnchorDistancesResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/GyroscopeResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MagnetometerResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
  docs/wifi_ble_communication_protocol.md
Labels: documentation, enhancement, test

#73 clients: Fix incorrect documentation
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Obstacle.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
Labels: documentation

#66 Refactor Alphabot.NET with present functionality
  emulator_tests/basic_steering_test.py
  rpi/Alphabot.Net/Alphabot.Net.Car/Alphabot.Net.Car.csproj
  rpi/Alphabot.Net/Alphabot.Net.Car/AlphabotCar.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Devices/AlphabotSpeedController.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Devices/CollisionPreventionAssist.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Devices/DualGearMotor.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Devices/GearMotor.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Devices/PositioningSystem.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Devices/SteeringStepper.cs
  rpi/Alphabot.Net/Alphabot.Net.Car/Steering/SteeringController.cs
  rpi/Alphabot.Net/Alphabot.Net.Cli/Program.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionBackward.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionCalibrateSteering.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionCenterSteering.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionFactory.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionForward.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionIdle.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSay.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetCollisionPrevention.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetSpeed.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetSteeringMethod.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionStop.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionTurn.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionTurnLeft.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionTurnRight.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/AlphabotAction.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Contracts/IAlphabotAction.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Contracts/IAlphabotRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Contracts/IClientHandler.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Contracts/ISessionHandler.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/ActionExecutor.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/AlphabotRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/BitProtocolParser.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/ClientHandler.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/SessionHandler.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/SystemHandler.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/Core/ToggleSettings.cs
  rpi/Alphabot.Net/Alphabot.Net.Remote/TcpService.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Contracts/IAlphabotRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Contracts/IAlphabotResponse.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Contracts/IServiceLogger.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Contracts/ISocketReader.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Contracts/ISocketWriter.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Delegates.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Models/Position.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Prefs/DeviceSettings.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Prefs/ServiceSettings.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/CalibrateSteeringRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/ConfigurePositioningAnchorRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/PingRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/SpeedSteerRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/ToggleRequest.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Responses/ErrorResponse.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Responses/PingResponse.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Responses/PositioningResponse.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/Responses/ToggleResponse.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/SocketReader.cs
  rpi/Alphabot.Net/Alphabot.Net.Shared/SocketWriter.cs
Labels: enhancement, Raspberry Pi

#79 docs: Add second wheel speed
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
  docs/wifi_ble_communication_protocol.md
Labels: documentation, enhancement, test

#80 clients/xamarin: Display ErrorResponse as DisplayAlert
  clients/XamarinClient/AlphabotXamarinClient/MainPage.xaml.cs
Labels: enhancement

#81 docs/protocol: Improve BLE response for obstacle removal
  docs/wifi_ble_communication_protocol.md
Labels: documentation, enhancement

#82 docs/protocol: Improve the wheel speed resolution
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
  clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
  docs/wifi_ble_communication_protocol.md
Labels: documentation, test
